2024-01-19 19:00:06 [INFO] - Log file created at /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_logs/AnalysisTest.log
2024-01-19 19:00:06 [INFO] - Setting up genpcap cli tool ...
2024-01-19 19:00:06 [INFO] - Running Test-Case 1
2024-01-19 19:00:07 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc1 -pt ipv4 -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:07 [INFO] - pcap saved in test_files as tc1.pcap
2024-01-19 19:00:07 [INFO] - Running Test-Case 2
2024-01-19 19:00:08 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:08 [INFO] - Running Test-Case 3
2024-01-19 19:00:08 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:08 [INFO] - Running Test-Case 4
2024-01-19 19:00:09 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:09 [INFO] - Running Test-Case 5
2024-01-19 19:00:10 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:10 [INFO] - Running Test-Case 6
2024-01-19 19:00:10 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:10 [INFO] - Running Test-Case 7
2024-01-19 19:00:11 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:11 [INFO] - Running Test-Case 8
2024-01-19 19:00:11 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:11 [INFO] - Running Test-Case 9
2024-01-19 19:00:12 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:12 [INFO] - Running Test-Case 10
2024-01-19 19:00:12 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:12 [INFO] - Running Test-Case 11
2024-01-19 19:00:13 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:13 [INFO] - Running Test-Case 12
2024-01-19 19:00:13 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:13 [INFO] - Running Test-Case 13
2024-01-19 19:00:14 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:14 [INFO] - Running Test-Case 14
2024-01-19 19:00:14 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:14 [INFO] - Running Test-Case 15
2024-01-19 19:00:15 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:15 [INFO] - Running Test-Case 16
2024-01-19 19:00:15 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:15 [INFO] - Running Test-Case 17
2024-01-19 19:00:16 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:16 [INFO] - Running Test-Case 18
2024-01-19 19:00:16 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:16 [INFO] - Running Test-Case 19
2024-01-19 19:00:17 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:17 [INFO] - Running Test-Case 20
2024-01-19 19:00:17 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:17 [INFO] - Running Test-Case 21
2024-01-19 19:00:18 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:18 [INFO] - Running Test-Case 22
2024-01-19 19:00:18 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:18 [INFO] - Running Test-Case 23
2024-01-19 19:00:19 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:19 [INFO] - Running Test-Case 24
2024-01-19 19:00:19 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:19 [INFO] - Running Test-Case 25
2024-01-19 19:00:20 [ERROR] - Invalid cli command did not raise error as expected
2024-01-19 19:00:20 [INFO] - Running Test-Case 26
2024-01-19 19:00:20 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc26 -hd ethernet -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:20 [INFO] - pcap saved in test_files as tc26.pcap
2024-01-19 19:00:20 [INFO] - Running Test-Case 27
2024-01-19 19:00:21 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc27 -pt vlan -vtt single -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:21 [INFO] - pcap saved in test_files as tc27.pcap
2024-01-19 19:00:21 [INFO] - Running Test-Case 28
2024-01-19 19:00:22 [ERROR] - There was a problem executing the test-case command:Command 'genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc28 -hd ethernet vlan  -vtt double-up 0x0000000000000000 -pkc 10 -pr 60' returned non-zero exit status 2.
2024-01-19 19:00:22 [INFO] - Running Test-Case 29
2024-01-19 19:00:22 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc29 -pt mpls -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:22 [INFO] - pcap saved in test_files as tc29.pcap
2024-01-19 19:00:22 [INFO] - Running Test-Case 30
2024-01-19 19:00:23 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc30 -hd ethernet ipv6 -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:23 [INFO] - pcap saved in test_files as tc30.pcap
2024-01-19 19:00:23 [INFO] - Running Test-Case 31
2024-01-19 19:00:23 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc31 -pt gtp -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:23 [INFO] - pcap saved in test_files as tc31.pcap
2024-01-19 19:00:23 [INFO] - Running Test-Case 32
2024-01-19 19:00:24 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc32 -hd ethernet ipv4 tcp -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:24 [INFO] - pcap saved in test_files as tc32.pcap
2024-01-19 19:00:24 [INFO] - Running Test-Case 33
2024-01-19 19:00:24 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc33 -pt udp -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:24 [INFO] - pcap saved in test_files as tc33.pcap
2024-01-19 19:00:24 [INFO] - Running Test-Case 34
2024-01-19 19:00:25 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc34 -hd ethernet ecpri -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:25 [INFO] - pcap saved in test_files as tc34.pcap
2024-01-19 19:00:25 [INFO] - Running Test-Case 35
2024-01-19 19:00:25 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc35 -pt roe -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:25 [INFO] - pcap saved in test_files as tc35.pcap
2024-01-19 19:00:25 [INFO] - Running Test-Case 36
2024-01-19 19:00:26 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc36 -hd ethernet ipv4 udp gtp -gv 1 -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:26 [INFO] - pcap saved in test_files as tc36.pcap
2024-01-19 19:00:26 [INFO] - Running Test-Case 37
2024-01-19 19:00:27 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc37 -pt gtp -gv 2 -up 0x0000000000000000 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:27 [INFO] - pcap saved in test_files as tc37.pcap
2024-01-19 19:00:27 [INFO] - Running Test-Case 38
2024-01-19 19:00:27 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc38 -pt ipv4 -np -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:27 [INFO] - pcap saved in test_files as tc38.pcap
2024-01-19 19:00:27 [INFO] - Running Test-Case 39
2024-01-19 19:00:28 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc39 -pt ipv4 -ifl 33 -isz 8 -flstp -3 -szstp 8 -mnsz 8 -mxsz 128  -szstp 8 -pkc 10 -pr 60', returncode=0)
2024-01-19 19:00:28 [INFO] - pcap saved in test_files as tc39.pcap
2024-01-19 19:00:28 [INFO] - Running Test-Case 40
2024-01-19 19:00:28 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc40 -pt ipv4 -up 0x0000000000000000 -pkc 10 -aipg 18 -ipgr 6', returncode=0)
2024-01-19 19:00:28 [INFO] - pcap saved in test_files as tc40.pcap
2024-01-19 19:00:28 [INFO] - Running Test-Case 41
2024-01-19 19:00:29 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc41 -pt ipv4 -up 0x0000000000000000 -tst 40 -aipg 3 -ipgr 0.5', returncode=0)
2024-01-19 19:00:29 [INFO] - pcap saved in test_files as tc41.pcap
2024-01-19 19:00:29 [INFO] - Running Test-Case 42
2024-01-19 19:00:31 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc42 -pt ipv4 -up 0x0000000000000000 -tst 55 -pr 60', returncode=0)
2024-01-19 19:00:31 [INFO] - pcap saved in test_files as tc42.pcap
2024-01-19 19:00:31 [INFO] - Running Test-Case 43
2024-01-19 19:00:31 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc43 -pt ipv4 -up 0x0000000000000000 -bc 300 -br 75', returncode=0)
2024-01-19 19:00:31 [INFO] - pcap saved in test_files as tc43.pcap
2024-01-19 19:00:31 [INFO] - Running Test-Case 44
2024-01-19 19:00:32 [INFO] - Successfully executed test-case process callCompletedProcess(args='genpcap.py -fn /home/elijah/pcap_tools_personal/tests/cli_ui_tests/test_files/tc44 -pt ipv4 -up 0x0000000000000000 -tst 67 -br 77', returncode=0)
2024-01-19 19:00:32 [INFO] - pcap saved in test_files as tc44.pcap
